version: "3.3"

services:
  webapp:
    image: pokemonrestapp:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    environment:
      - DB_CONN_STRING=mysql://playground:playground@mysql:3306/playground
      - ALLOWED_ORIGINS=http://localhost,http://localhost:8080,http://localhost:3000,https://pensive-raman-3248b3.netlify.app
    depends_on:
      - mysql

  mysql:
    image: "bitnami/mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=playground
      - MYSQL_USER=playground
      - MYSQL_PASSWORD=playground
      - MYSQL_DATABASE=playground
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3306:3306"
